export type Project = {
  _id: string;
  user: string;
  title: string;
  description: string;
  designer: string;
  applicationType: string;
  budget: string;
  isPublic: boolean;
  client: string;
  images: string[];
  trelloUrl: string;
  githubUrl: string;
  projectUrl: string;
  techStack: string[];
  tags: string[];
  developerFeedback: any[];
  relatedProjects: any[];
  status: string;
  createdAt: string;
  updatedAt: string;
};
